---
title: How to FULLY Customize Leaflet Maps using R programming
format:
  html:
    toc: true
    number-sections: true
    css: styles.css
---

## Pacotes necessários
Checar se tem todos os pacotes necessários. Caso não tenha, instalar os que faltam.
```{r}  
#| label: install_packcages
#| fig-cap: "Bloco para instalação de pacotes"
#| warning: false
# pacotes necessários
libs <- c(
    "tidyverse", # data manipulation
    "leaflet", # leaflet library
    "leaflet.extras", # extras of leaflet
    "sf", # geodata manipulation
    "knitr", # for kable tables
    "BFS" # Swiss Federal Statistical Office Data
)

# checar se todos os pacotes necessários já estão instalados
installed_libs <- libs %in% rownames(
    installed.packages()
)

# instalar pacotes que não estão instalados
if(any(installed_libs == FALSE)){
    install.packages(
        libs[!installed_libs]
    )
}

# carregar pacotes (etapa opcional)
invisible(lapply(
    libs, library,
    character.only = T
))

```


```{r}

tables_names <- BFS::bfs_get_catalog_tables(
    language =  "en",
    title = "last+names"
)

```


```{r}

asset_names_commune <- tables_names |>
    dplyr::filter(stringr::str_detect(title, "commune")) |>
    dplyr::pull(number_asset)

# apenas o primeiro item da lista
asset_names_commune <- asset_names_commune[1]


```

